version: 2
jobs:
    test:
        working_directory: ~/code
        docker:
            - image: node:11.9.0
        steps:
            - checkout
            - restore_cache:
                  key: npm-cache-v1-{{ checksum "package-lock.json" }}
            - run:
                  name: Install Dependencies
                  command: npm ci
            - save_cache:
                  key: npm-cache-v1-{{ checksum "package-lock.json" }}
                  paths:
                      - /home/circleci/.npm
            - run:
                  name: Build
                  command: npm run build
            - run:
                  name: Run Tests
                  command: npm test

    build_and_push_image:
        working_directory: ~/code
        docker:
            - image: node:11.9.0
        steps:
            - checkout
            - setup_remote_docker
            - run:
                  name: Install Docker client
                  command: |
                      set -x
                      VER="17.03.0-ce"
                      curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
                      tar -xz -C /tmp -f /tmp/docker-$VER.tgz
                      mv /tmp/docker/* /usr/bin
            - run:
                  name: Building the image
                  command: |
                      TAG=${CIRCLE_BRANCH}
                      docker build -t unicef/etools-manage:$TAG .
            - run:
                  name: Pushing to Docker Hub
                  command: |
                      TAG=${CIRCLE_BRANCH}
                      docker login -u $DOCKER_USER -p $DOCKER_PASS
                      docker push unicef/etools-manage:$TAG

    deploy:
        docker:
            - image: jonaskello/rancher-cli-k8s:v2.0.4
        steps:
            - run:
                  name: Rancher Login
                  command: rancher login $RANCHER2_SERVER_URL --token $RANCHER2_BEARER_TOKEN --context $RANCHER_CONTEXT
            - run:
                  name: Patch Deploy
                  command: rancher kubectl --namespace=etools-dev patch deployment manage-app -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"date\":\"`date +'%s'`\"}}}}}"

workflows:
    version: 2
    build_and_test:
        jobs:
            - test
            - build_and_push_image:
                  requires:
                      - test
                  filters:
                      branches:
                          only:
                              - master
                              - staging
                              - develop
                              - build-fix
            - deploy:
                  requires:
                      - test
                      - build_and_push_image
                  filters:
                      branches:
                          only:
                              - master
                              - staging
                              - develop
                              - build-fix
